### ISSUE TITLE
Setting a thread's name?

### ISSUE THREAD

**Issue by bra-fsn** [rfk/threading2#2]
It would be nice to have thread-naming available in this module. Python's standard library has (also) the name attribute, but doesn't set it.

See:
http://stackoverflow.com/questions/2369738/can-i-set-the-name-of-a-thread-in-pthreads-linux
drfrogsplat's answer seem to be the right way to do this on those platforms.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
