### ISSUE TITLE
Testing thread priority

### ISSUE THREAD

**Issue by lromor** [rfk/threading2#6]
I have a question, I tried to test the priority feature of this library with the following code:

``` python
import threading2
import time

start_threads = threading2.Event()

def test():
    while start_threads.is_set() is False:
        continue
    print "THREAD "+ str(threading2.currentThread().name)+" STARTED!"
    k=0
    for i in range(0,1000000):

        k = k +1

    print "THREAD: " + str(threading2.currentThread().name) + " k: " + str(k)

lowp=1
highp=1
cp=0

lp1 = threading2.Thread(name="LOW1",target=test,priority=lowp)
lp2 = threading2.Thread(name="LOW2",target=test,priority=lowp)
lp3 = threading2.Thread(name="LOW3",target=test,priority=lowp)
lp4 = threading2.Thread(name="LOW4",target=test,priority=lowp)
lp5 = threading2.Thread(name="LOW5",target=test,priority=lowp)
lp6 = threading2.Thread(name="LOW6",target=test,priority=lowp)
lp7 = threading2.Thread(name="LOW7",target=test,priority=lowp)
lp8 = threading2.Thread(name="LOW8",target=test,priority=lowp)

hp1 = threading2.Thread(name="HP1",target=test,priority=highp)
hp2 = threading2.Thread(name="HP2",target=test,priority=highp)
hp3 = threading2.Thread(name="HP3",target=test,priority=highp)
hp4 = threading2.Thread(name="HP4",target=test,priority=highp)
hp5 = threading2.Thread(name="HP5",target=test,priority=highp)
hp6 = threading2.Thread(name="HP6",target=test,priority=cp)
hp7 = threading2.Thread(name="HP7",target=test,priority=highp)
hp8 = threading2.Thread(name="HP8",target=test,priority=highp)


lp1.start()
lp2.start()
lp3.start()
lp4.start()
lp5.start()
lp6.start()
lp7.start()
lp8.start()

hp1.start()
hp2.start()
hp3.start()
hp4.start()
hp5.start()
hp6.start()
hp7.start()
hp8.start()

print "READY TO GO!"
start_threads.set()
```

I made 8 threads in such a way we have a big pool of concurrent threads, 7 of them with a priority 1 and one(hp6) with a custom priority 0  (don't look at the variables names). I was expecting the hp6 thread to be the last(or maybe the first) but in the end the final result was random. I am missing something I think, could you help me?

**Comment by rfk** [comment]
Hi @leonardoromor, sorry for leaving this unanswered for so long, unfortunately I don't have much bandwidth for maintenance of the project these days.  If you're still interested in digging into this, can you please let me know what platform you're on?  The library does a best-effort attempt to setting priority etc, but it's not always possible or reliable on all platforms.

**Comment by leonardoromor** [comment]
hi @rfk 
I tested it on:
Linux beaglebone 3.8.13-bone47 #1 SMP armv7l GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.4 (wheezy)

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
